import { Poppins } from "next/font/google"; // Use only Poppins
import "./globals.css";
import Navbar from "../compnents/navbar/Navbar"; // Adjust the import path as needed

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body className={`${poppins.variable} antialiased`}>
        {children}

 
      </body>
    </html>
  );
}
